apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd  # Same common label to match both deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 8080

service file :-
apiVersion: v1
kind: Service
metadata:
  name: my-httpdservice
spec:
  type: NodePort
  selector:
    app: httpd  # Matches httpd deployment
  ports:
    - name: httpd-port  # Name for the httpd port
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Expose httpd on NodePort 30001